### PR TITLE
added assembly shade support

### PR DESCRIPTION
**Pull request by brkyvz**
Adds support for a shaded jar to be used for packaging.

All that is required is that `assembly in spPackage` to be set for the minimal shaded assembly jar.
This can be set as `assembly in spPackage := assembly.value` if the assembly jar doesn't contain any transitive dependencies.

### CODE REVIEW

**Comment by brkyvz** [comment]
cc @	pkolaczk @RussellSpitzer @thunterdb

**Comment by pkolaczk** [comment]
Looks like it works. It works even without setting  `assembly in spPackage` - it just uses the same shaging config I have for `sbt assembly` task.

**Comment by brkyvz** [comment]
Great! It would use the default config if you don't set it, however I would like people to set it so that they don't upload a full assembly jar, but only the shaded parts of the jar. The only missing part is the modifications in the pom (removing shaded jars from pom).

**Comment by pkolaczk** [comment]
Ah, so if I add `assembly in spPackage := assembly.value` - that will include only the shaded parts of the jar right?

**Comment by brkyvz** [comment]
Right now it includes everything in the original `assembly` definition. Therefore it may be the full fat jar.
You need to make sure that it gets only the shaded dependencies with your assembly configurations. I'm going to try and do it for tensorframes. once I have a working example, I will ping you on it.

**Comment by pkolaczk** [comment]
But why should I exclude things that are not shaded from the spark package? E.g. we include Cassandra driver, which is mandatory for the connector, but can't shade it because it exposes a few things in the public API.

**Comment by brkyvz** [comment]
@pkolaczk You can try something like here:
https://github.com/databricks/sbt-spark-package/pull/23/files#diff-8d43497dc5589963f0135df6da0a15dcR7

Basically, you need one project that doesn't include anything else but shaded dependencies and code in it, then you need one project which has all the non shaded dependencies and the plugin settings.
Does that make sense? The plugin will pickup the shaded jar during compilation and use it as the jar.

**Comment by RussellSpitzer** [comment]
This only adjusts spDist? Shouldn't it change spPublish and PublishLocal as well?

**Comment by RussellSpitzer** [comment]
The spDist command works for us, it correctly puts the POM and shaded jar in place. I had no problems even with my limited SBT knowledge to get this working. I'm still trying to figure out how to make our normal maven artifacts look the same :)


 I do wonder if we want to have it edit the pom file to exclude the shaded deps, but that's not super important.

**Comment by brkyvz** [comment]
@RussellSpitzer The pom should be clean, it shouldn't contain the shaded dependencies if you don't add the dependencies inside the `libraryDependencies` field in your distribution project. Thanks for the comments, I'm going to merge this in, and make a new release.
Let me know if you need any help in configuring your project.

**Comment by thunterdb** [comment]
Thanks Burak!




On August 15, 2016 at 10:44:39 AM, Burak Yavuz (notifications@github.com)
wrote:

Closed #23 <https://github.com/databricks/sbt-spark-package/pull/23>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/databricks/sbt-spark-package/pull/23#event-755964886>,
or mute the thread

**Pull request closed without merging**
